// import ShopDetailMapper from "@/api/dataSource/api/plugins/models/mapModel/shop/ShopDetailMaperModel"
// import ShopDetailItem from "@/api/dataSource/api/plugins/models/controllersModels/shops/ShopDetailItem"
// export default class ShopMapper {
//     static fromServerModel(r: ShopDetailItem): ShopDetailMapper {
//         return new ShopDetailMapper({
//             Id: r.Id,
//             Code: r.Code,
//             Name: r.Name,
//             FullName: r.FullName,
//             CassaSoft:r.CassaSoft,
//             Enterprise: {
//                 State:r.Enterprise.State,
//                 TimeDifferenceHours:r.Enterprise.TimeDifferenceHours,
//                 QlaunchOperators:r.Enterprise.QlaunchOperators,
//                 PosCode:r.Enterprise.PosCode,
//                 Shops:r.Enterprise.Shops,
//                 PaymentType:r.Enterprise.PaymentType,
//                 Operators:r.Enterprise.Operators,
//                 NdsCodeDe:r.Enterprise.NdsCodeDe,
//                 EntCodeDe:r.Enterprise.EntCodeDe,
//                 Code:r.Enterprise.Code,
//                 ContractDate:r.Enterprise.ContractDate,
//                 ContractNumber:r.Enterprise.ContractNumber,
//                 Account:r.Enterprise.Account,
//                 Account2:r.Enterprise.Account2,
//                 Id:r.Enterprise.Id,
//                 IsBlocked: r.Enterprise.IsBlocked,
//                 IsNdsPayer: r.Enterprise.IsNdsPayer,
//                 IsMini: r.Enterprise.IsMini,
//                 Name: r.Enterprise.Name,
//                 FullName: r.Enterprise.FullName,
//                 Address: r.Enterprise.Address,
//                 PostAddress: r.Enterprise.PostAddress,
//                 Phone: r.Enterprise.Phone,
//                 Fax: r.Enterprise.Fax,
//                 Email: r.Enterprise.Email,
//                 BankRequisite: r.Enterprise.BankRequisite,
//                 BillingType: r.Enterprise.BillingType,
//                 Inn: r.Enterprise.Inn,
//                 Kpp: r.Enterprise.Kpp,
//                 CashRegister: r.Enterprise.CashRegister,
//                 Editor : r.Enterprise.Editor,
//                 TimeDifference: r.Enterprise.TimeDifference,
//                 FullPayment: r.Enterprise.FullPayment,
//                 AddBalanceType: r.Enterprise.AddBalanceType,
//                 RewardFromPayPercent: r.Enterprise.RewardFromPayPercent,
//                 RewardFromPayAmount: r.Enterprise.RewardFromPayAmount,
//                 InsuredLimit: r.Enterprise.InsuredLimit,
//                 InsuredBlockSum: r.Enterprise.InsuredBlockSum,
//                 InsuredBlockPrice: r.Enterprise.InsuredBlockPrice,
//                 InsuredBlockEndDate: r.Enterprise.InsuredBlockEndDate,
//                 IsVerified: r.Enterprise.IsVerified,
//                 DaysForPay: r.Enterprise.DaysForPay,
//                 AgreementAmount: r.Enterprise.AgreementAmount,
//                 ExtraLimit: r.Enterprise.ExtraLimit,
//                 ReportSendPeriodicity: r.Enterprise.ReportSendPeriodicity,
//                 EmoneyRegistrationCoast: r.Enterprise.EmoneyRegistrationCoast,
//                 IsCreatePayment: r.Enterprise.IsCreatePayment,
//                 LastReportDate: r.Enterprise.LastReportDate,
//                 ReportSendTime: r.Enterprise.ReportSendTime,
//                 ChildEntIdList: r.Enterprise.ChildEntIdList,
//                 AllowedCurrencyList: r.Enterprise.AllowedCurrencyList,
//                 SignaturePosition: r.Enterprise.SignaturePosition,
//                 SignatureFIO: r.Enterprise.SignatureFIO,
//                 ChiefAccountantFio: r.Enterprise.ChiefAccountantFio,
//                 CuratorFio: r.Enterprise.CuratorFio,
//                 InsertEncashmentPayment: r.Enterprise.InsertEncashmentPayment,
//                 ChangeTranDate: r.Enterprise.ChangeTranDate,
//                 ShowInReport: r.Enterprise.ShowInReport,
//                 BalanceRecalc: r.Enterprise.BalanceRecalc,
//                 ActHeader: r.Enterprise.ActHeader,
//                 EmailSendPeriodicity: r.Enterprise.EmailSendPeriodicity,
//                 Notes: r.Enterprise.Notes,
//                 DateAdd: r.Enterprise.DateAdd,
//                 DateChange: r.Enterprise.DateChange,
//                 ProvisionModel: r.Enterprise.ProvisionModel,
//                 IsBalanceFromLastAct: r.Enterprise.IsBalanceFromLastAct, 
//                 MaxLimitSize : r.Enterprise.MaxLimitSize,
//             },
//             Agent: {
//                 Id: r.Agent?.Id,
//                 Avatar:r.Agent?.Avatar,
//                 BelongsToGroups:r.Agent?.BelongsToGroups,
//                 DateChange:r.Agent?.DateChange,
//                 Editor:r.Agent?.Editor,
//                 Email:r.Agent?.Email ,
//                 Enterprise:r.Agent?.Enterprise,
//                 EnterpriseId:r.Agent?.EnterpriseId ,
//                 Fax:r.Agent?.Fax,
//                 FullName:r.Agent?.FullName ,
//                 GoogleAuthSecretKey:r.Agent?.GoogleAuthSecretKey,
//                 IsBackOfficeUser:r.Agent?.IsBackOfficeUser,
//                 IsBlocked:r.Agent?.IsBlocked,
//                 IsContactOnly:r.Agent?.IsContactOnly,
//                 IsPrepaid:r.Agent?.IsPrepaid,
//                 IsRewardCalc:r.Agent?.IsRewardCalc,
//                 IsShopUser:r.Agent?.IsShopUser,
//                 MobilePhone:r.Agent?.MobilePhone,
//                 Name:r.Agent?.Name,
//                 Notes:r.Agent?.Notes,
//                 Password:r.Agent?.Password,
//                 Phone: r.Agent?.Phone,
//                 Rights:r.Agent?.Rights,
//                 ShopIds:r.Agent?.ShopIds,
//                 State:r.Agent?.State,
//                 TrnCopySumLimit:r.Agent?.TrnCopySumLimit ,
//                 UserEnts:r.Agent?.UserEnts,
//                 UserName:r.Agent?.UserName,
//                 UserShops:r.Agent?.UserShops,
//             },
//             Represantative: {
//                 Id: r.Represantative?.Id
//             },
//             BrendName: r.BrendName,
//             Address: r.Address,
//             Phone: r.Phone,
//             Fax: r.Fax,
//             BillingType: r.BillingType,
//             Notes: r.Notes,
//             DateAdd: r.DateAdd,
//             DateChange: r.DateChange,
//             Editor: {
//                 UserEnts: r.Editor.UserEnts,
//                 Avatar: r.Editor.Avatar,
//                 BelongsToGroups: r.Editor.BelongsToGroups,
//                 DateChange: r.Editor.DateChange,
//                 Editor: r.Editor.Editor,
//                 Email: r.Editor.Email,
//                 Enterprise: r.Editor.Enterprise,
//                 EnterpriseId: r.Editor.EnterpriseId,
//                 Fax: r.Editor.Fax,
//                 FullName: r.Editor.FullName,
//                 GoogleAuthSecretKey: r.Editor.GoogleAuthSecretKey,
//                 Id: r.Editor.Id,
//                 IsBackOfficeUser: r.Editor.IsBackOfficeUser,
//                 IsBlocked: r.Editor.IsBlocked,
//                 IsContactOnly: r.Editor.IsContactOnly,
//                 IsPrepaid: r.Editor.IsPrepaid,
//                 IsRewardCalc: r.Editor.IsRewardCalc,
//                 IsShopUser: r.Editor.IsShopUser,
//                 MobilePhone: r.Editor.MobilePhone,
//                 Name: r.Editor.Name,
//                 Notes: r.Editor.Notes,
//                 Password: r.Editor.Password,
//                 Phone: r.Editor.Phone,
//                 Rights: r.Editor.Rights,
//                 ShopIds: r.Editor.ShopIds,
//                 State: r.Editor.State,
//                 TrnCopySumLimit: r.Editor.TrnCopySumLimit,
//                 UserName: r.Editor.UserName,
//                 UserShops: r.Editor.UserShops,
//             },
//             State : r.State,
//         })
//     }
//     static toServerModel(r: ShopDetailMapper): ShopDetailItem {
//         return {

//         };
//     }

// }