export default class PaymentsListRequest {
    EnterpriseId?:number
    ShopId?:number
    PosCode?:string
    PosTypeId?:number
    StatusId?:number
    StatusDateTypeId?:number
    OnlyTranCopies?:boolean
    Phone?:string
    Id?:number
    Note?:string
    IdN4Check?:number
    IdOperator?:number
    GatewayId?:number
    OperatorId?:number
    PaymentTypeId?:number
    IdFiscal?:number
    DateStart?:Date
    DateEnd?:Date
}