export default class Agent {
    Avatar?: any
    BelongsToGroups?: any
    DateChange?: Date
    Editor?: string
    Email?: string
    Enterprise?: any
    EnterpriseId?: number
    Fax?: string
    FullName?: string
    GoogleAuthSecretKey?: any
    Id?: number
    IsBackOfficeUser?: boolean
    IsBlocked?: boolean
    IsContactOnly?: boolean
    IsPrepaid?: boolean
    IsRewardCalc?: boolean
    IsShopUser?: boolean
    MobilePhone?: any
    Name?: string
    Notes?: string
    Password?: string
    Phone?: string
    Rights?: any
    ShopIds?: any
    State?: number
    TrnCopySumLimit?: any
    UserEnts?: any
    UserName?: string
    UserShops?: any
}