export default class PointOfSalesMonitoringDetailItem {
    Address?: any
    BanknotesMaxCount?: number
    BeepayPosCode?: any
    BusinessHours?: any
    CalculatedAddress?: any
    CoinsMaxCount?: number
    Color?: any
    Curator?: any
    DateChange?:Date
    DayLimit?: number
    DeviceType?: any
    DispenserUse?: false
    Editor?: any
    Id?: number
    IsMonitoring?: number
    JurAdress?: any
    Latitude?: any
    Longtitude?: any
    Mobile?: any
    MonthLimit?: number
    N4AliveTimeout?: number
    N4GWVersion?: any
    Name?: any
    Notes?: any
    Online?: number
    Password?: any
    PrevPosId?: number
    RegistrationStatus?: number
    RejectPercent?: any
    Rssi?: any
    SerialNum?: any
    Shop?: any
    ShopPosCode?: any
    SoftVersion?: any
    State?: number
    TerminalPlaceComment1?: any
    TerminalState?: number
    TerminalStateComment?: any
    TopAdvertise?: any
    Type?: any
    WeekLimit?: number
    Weekends?: any
    pos_LAST_N4UPLOAD_DATE?: Date
}