export default class ContractDetailItem{
    Id?:number
    CounterAgent?:string
    ContractNumber?:string
    ContractDate?:Date
    Contracter?:string
    Account?:string
    Account2?:string
    ParentName?:string
    AccountsByGroups?:any
    Bik?:any
    ContractFull?:string
    CounterAgentFull?:string
    CounterAgentState?:boolean
    DateChange?:Date
    DateTo?:Date
    Editor?:any
    EnterpriseId?:number
    GatewayId?:number
    Name?:string
    ParentId?:number
    PayDelay?:number
    ThirdPartnerEnterprise?:any
    ThirdPartnerId?:number
    contractPartner?:any
    enterprise?:any
    СontractPartnerId?:number
}